create table booking (booking_id bigint not null auto_increment, trip_id bigint not null, user_id bigint not null, status varchar(255), primary key (booking_id)) engine=InnoDB;
create table booking_group (booking_id bigint, group_id bigint not null auto_increment, primary key (group_id)) engine=InnoDB;
create table booking_package_relation (booking_id bigint not null, package_id bigint not null) engine=InnoDB;
create table booking_room_relation (booking_id bigint not null, stateroom_id bigint not null) engine=InnoDB;
create table entertainment (floor integer not null, entertainment_id bigint not null auto_increment, description varchar(1024), entertainment_type varchar(255), name varchar(255), status varchar(255), primary key (entertainment_id)) engine=InnoDB;
create table invoice (status integer not null, booking_id bigint not null, invoice_id bigint not null auto_increment, money bigint not null, description varchar(1024), name varchar(255), primary key (invoice_id)) engine=InnoDB;
create table location (location_id bigint not null auto_increment, location varchar(255), primary key (location_id)) engine=InnoDB;
create table package (price integer not null, package_id bigint not null auto_increment, description varchar(1024), charge_type varchar(255), name varchar(255), status varchar(255), primary key (package_id)) engine=InnoDB;
create table passenger (dob datetime(6) not null, group_id bigint not null, passenger_id bigint not null auto_increment, city varchar(255), country varchar(255) not null, email varchar(255) not null, first_name varchar(255) not null, gender varchar(255) not null, last_name varchar(255) not null, phone varchar(255) not null, state varchar(255), street varchar(255), primary key (passenger_id)) engine=InnoDB;
create table payment (booking_id bigint, invoice_id bigint, payment_amount bigint not null, payment_date datetime(6), payment_id bigint not null auto_increment, payment_method varchar(255), primary key (payment_id)) engine=InnoDB;
create table port (parking_spots integer not null, port_id bigint not null auto_increment, nearest_airport varchar(1024), address varchar(255), country varchar(255), name varchar(255), state varchar(255), status varchar(255), primary key (port_id)) engine=InnoDB;
create table restaurant (floor integer not null, restaurant_id bigint not null auto_increment, description varchar(1024), name varchar(255), restaurant_type varchar(255), serving_time varchar(255), status varchar(255), primary key (restaurant_id)) engine=InnoDB;
create table state_room_price (price_night integer not null, stateroom_id bigint not null, trip_id bigint not null, primary key (stateroom_id, trip_id)) engine=InnoDB;
create table stateroom (balcony_count integer not null, number_bath float(23) not null, number_beds integer not null, room_size integer not null, location_id bigint, stateroom_id bigint not null auto_increment, stateroom_type varchar(255), status varchar(255), primary key (stateroom_id)) engine=InnoDB;
create table token_entity (create_time datetime(6), id bigint not null auto_increment, user_id bigint, token varchar(255), primary key (id)) engine=InnoDB;
create table trip (trip_nights integer not null, end_date datetime(6), end_port_id bigint, start_date datetime(6), start_port_id bigint, trip_id bigint not null auto_increment, name varchar(255), status varchar(255), primary key (trip_id)) engine=InnoDB;
create table trip_entertainment_relation (entertainment_id bigint not null, trip_id bigint not null) engine=InnoDB;
create table trip_port_info (arrival_date datetime(6), departure_date datetime(6), port_id bigint not null, trip_id bigint not null, primary key (port_id, trip_id)) engine=InnoDB;
create table trip_restaurant_relation (restaurant_id bigint not null, trip_id bigint not null) engine=InnoDB;
create table user (create_time datetime(6), id bigint not null auto_increment, password varchar(255), role varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
alter table booking_group add constraint UK_1wf4jfxionqp1d1gk2j224gku unique (booking_id);
alter table payment add constraint UK_4l6ndm1m1iw9knbdtxd6m6fyc unique (invoice_id);
alter table user add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table booking add constraint FKkp5ujmgvd2pmsehwpu2vyjkwb foreign key (trip_id) references trip (trip_id);
alter table booking add constraint FKkgseyy7t56x7lkjgu3wah5s3t foreign key (user_id) references user (id);
alter table booking_group add constraint FKl6ww7wnye25uyj79jqpipjqh4 foreign key (booking_id) references booking (booking_id);
alter table booking_package_relation add constraint FKdljfu2kjugu1lw9uqslubdmr3 foreign key (package_id) references package (package_id);
alter table booking_package_relation add constraint FK2odctvtpk01i38dsd0825urdi foreign key (booking_id) references booking (booking_id);
alter table booking_room_relation add constraint FK5jfnqq0r50ob892949xux09yq foreign key (stateroom_id) references stateroom (stateroom_id);
alter table booking_room_relation add constraint FKk1bjo0die04irkovor4qbgt5c foreign key (booking_id) references booking (booking_id);
alter table invoice add constraint FK4jd6uuk7w0d72riyre2w14fl7 foreign key (booking_id) references booking (booking_id);
alter table passenger add constraint FKeateoof69n00ypusn8kqcse5 foreign key (group_id) references booking_group (group_id);
alter table payment add constraint FKqewrl4xrv9eiad6eab3aoja65 foreign key (booking_id) references booking (booking_id);
alter table payment add constraint FKsb24p8f52refbb80qwp4gem9n foreign key (invoice_id) references invoice (invoice_id);
alter table state_room_price add constraint FK916kot45w9de17qhqswchf64i foreign key (stateroom_id) references stateroom (stateroom_id);
alter table state_room_price add constraint FK6g5shiu4r9jnkijdiikematp0 foreign key (trip_id) references trip (trip_id);
alter table stateroom add constraint FK5ol08l3hekbl6hytjffodnnfj foreign key (location_id) references location (location_id);
alter table token_entity add constraint FKb1qudrv4v5lbo2useyi6iq6qb foreign key (user_id) references user (id);
alter table trip add constraint FK95yaoe4vn1v8acajqanw449eu foreign key (end_port_id) references port (port_id);
alter table trip add constraint FKj157737ledom26yiimgnq8rwf foreign key (start_port_id) references port (port_id);
alter table trip_entertainment_relation add constraint FKq6h58hg9qa4axq1wf57dooc13 foreign key (entertainment_id) references entertainment (entertainment_id);
alter table trip_entertainment_relation add constraint FKhnuf7c606ln3s59bfe9ikpgrg foreign key (trip_id) references trip (trip_id);
alter table trip_port_info add constraint FK96g6k2y67rtj2ukikc9eaf5gq foreign key (port_id) references port (port_id);
alter table trip_port_info add constraint FKbkpw08y00tuiuu8a0ovc6fu20 foreign key (trip_id) references trip (trip_id);
alter table trip_restaurant_relation add constraint FK1tdvfttjxrseru8fhgcov5m0m foreign key (restaurant_id) references restaurant (restaurant_id);
alter table trip_restaurant_relation add constraint FK3jn6lfly4yevi489634l3ama2 foreign key (trip_id) references trip (trip_id);
