INSERT INTO invoice (status, booking_id, invoice_id, money, description, name) VALUES (0, 1, 1, 4472, 'The initial bill: 1rooms, 3 passengers, 2 packages', 'Basic Bill');
INSERT INTO invoice (status, booking_id, invoice_id, money, description, name) VALUES (0, 2, 2, 6564, 'The initial bill: 2rooms, 3 passengers, 2 packages', 'Basic Bill');
INSERT INTO invoice (status, booking_id, invoice_id, money, description, name) VALUES (0, 3, 3, 5700, 'The initial bill: 1rooms, 2 passengers, 2 packages', 'Basic Bill');
INSERT INTO invoice (status, booking_id, invoice_id, money, description, name) VALUES (0, 4, 4, 5359, 'The initial bill: 4rooms, 3 passengers, 2 packages', 'Basic Bill');
INSERT INTO invoice (status, booking_id, invoice_id, money, description, name) VALUES (0, 5, 5, 2238, 'The initial bill: 3rooms, 2 passengers, 2 packages', 'Basic Bill');
INSERT INTO invoice (status, booking_id, invoice_id, money, description, name) VALUES (0, 6, 6, 9918, 'The initial bill: 3rooms, 1 passengers, 2 packages', 'Basic Bill');
INSERT INTO invoice (status, booking_id, invoice_id, money, description, name) VALUES (0, 7, 7, 620, 'The initial bill: 2rooms, 3 passengers, 0 packages', 'Basic Bill');
INSERT INTO invoice (status, booking_id, invoice_id, money, description, name) VALUES (0, 8, 8, 1150, 'The initial bill: 2rooms, 3 passengers, 1 packages', 'Basic Bill');
INSERT INTO invoice (status, booking_id, invoice_id, money, description, name) VALUES (0, 9, 9, 2040, 'The initial bill: 4rooms, 3 passengers, 2 packages', 'Basic Bill');
INSERT INTO invoice (status, booking_id, invoice_id, money, description, name) VALUES (0, 10, 10, 5731, 'The initial bill: 2rooms, 3 passengers, 2 packages', 'Basic Bill');
INSERT INTO invoice (status, booking_id, invoice_id, money, description, name) VALUES (0, 11, 11, 5515, 'The initial bill: 2rooms, 3 passengers, 2 packages', 'Basic Bill');
INSERT INTO invoice (status, booking_id, invoice_id, money, description, name) VALUES (0, 12, 12, 1700, 'The initial bill: 2rooms, 2 passengers, 1 packages', 'Basic Bill');
INSERT INTO invoice (status, booking_id, invoice_id, money, description, name) VALUES (0, 13, 13, 435, 'The initial bill: 2rooms, 1 passengers, 1 packages', 'Basic Bill');
INSERT INTO invoice (status, booking_id, invoice_id, money, description, name) VALUES (0, 14, 14, 6747, 'The initial bill: 3rooms, 3 passengers, 2 packages', 'Basic Bill');
INSERT INTO invoice (status, booking_id, invoice_id, money, description, name) VALUES (0, 15, 15, 4725, 'The initial bill: 2rooms, 2 passengers, 1 packages', 'Basic Bill');
INSERT INTO invoice (status, booking_id, invoice_id, money, description, name) VALUES (0, 16, 16, 2940, 'The initial bill: 1rooms, 3 passengers, 2 packages', 'Basic Bill');
INSERT INTO invoice (status, booking_id, invoice_id, money, description, name) VALUES (0, 17, 17, 950, 'The initial bill: 2rooms, 2 passengers, 1 packages', 'Basic Bill');
INSERT INTO invoice (status, booking_id, invoice_id, money, description, name) VALUES (0, 18, 18, 1680, 'The initial bill: 2rooms, 2 passengers, 1 packages', 'Basic Bill');
INSERT INTO invoice (status, booking_id, invoice_id, money, description, name) VALUES (0, 17, 19, -105, 'Update bookings: 2rooms, 2 passengers, 1 packages', 'BookingUpdate');
INSERT INTO invoice (status, booking_id, invoice_id, money, description, name) VALUES (0, 17, 20, -45, 'Update bookings: 1rooms, 2 passengers, 1 packages', 'BookingUpdate');
INSERT INTO invoice (status, booking_id, invoice_id, money, description, name) VALUES (0, 17, 21, 480, 'Update bookings: 1rooms, 2 passengers, 2 packages', 'BookingUpdate');
INSERT INTO invoice (status, booking_id, invoice_id, money, description, name) VALUES (0, 19, 22, 2120, 'The initial bill: 1rooms, 1 passengers, 1 packages', 'Basic Bill');
INSERT INTO invoice (status, booking_id, invoice_id, money, description, name) VALUES (0, 20, 23, 400, 'The initial bill: 2rooms, 2 passengers, 0 packages', 'Basic Bill');
INSERT INTO invoice (status, booking_id, invoice_id, money, description, name) VALUES (0, 21, 24, 120, 'The initial bill: 3rooms, 3 passengers, 0 packages', 'Basic Bill');
INSERT INTO invoice (status, booking_id, invoice_id, money, description, name) VALUES (0, 22, 25, 360, 'The initial bill: 1rooms, 2 passengers, 0 packages', 'Basic Bill');
INSERT INTO invoice (status, booking_id, invoice_id, money, description, name) VALUES (0, 23, 26, 2616, 'The initial bill: 2rooms, 2 passengers, 1 packages', 'Basic Bill');
INSERT INTO invoice (status, booking_id, invoice_id, money, description, name) VALUES (0, 21, 27, 1410, 'Update bookings: 3rooms, 3 passengers, 2 packages', 'BookingUpdate');
INSERT INTO invoice (status, booking_id, invoice_id, money, description, name) VALUES (0, 23, 28, 1800, 'Update bookings: 2rooms, 3 passengers, 1 packages', 'BookingUpdate');
INSERT INTO invoice (status, booking_id, invoice_id, money, description, name) VALUES (0, 6, 29, 11040, 'Update bookings: 3rooms, 3 passengers, 2 packages', 'BookingUpdate');
INSERT INTO invoice (status, booking_id, invoice_id, money, description, name) VALUES (0, 8, 30, 5160, 'Update bookings: 2rooms, 3 passengers, 2 packages', 'BookingUpdate');
INSERT INTO invoice (status, booking_id, invoice_id, money, description, name) VALUES (0, 9, 31, 635, 'Update bookings: 3rooms, 3 passengers, 3 packages', 'BookingUpdate');
INSERT INTO invoice (status, booking_id, invoice_id, money, description, name) VALUES (0, 8, 32, 7740, 'Update bookings: 2rooms, 3 passengers, 3 packages', 'BookingUpdate');
INSERT INTO invoice (status, booking_id, invoice_id, money, description, name) VALUES (0, 1, 33, 3086, 'Update bookings: 2rooms, 3 passengers, 3 packages', 'BookingUpdate');
INSERT INTO invoice (status, booking_id, invoice_id, money, description, name) VALUES (0, 4, 34, -150, 'Update bookings: 3rooms, 3 passengers, 2 packages', 'BookingUpdate');
INSERT INTO invoice (status, booking_id, invoice_id, money, description, name) VALUES (0, 4, 35, -150, 'Update bookings: 2rooms, 3 passengers, 2 packages', 'BookingUpdate');
INSERT INTO invoice (status, booking_id, invoice_id, money, description, name) VALUES (0, 4, 36, 1920, 'Update bookings: 2rooms, 3 passengers, 3 packages', 'BookingUpdate');
INSERT INTO invoice (status, booking_id, invoice_id, money, description, name) VALUES (0, 4, 37, 500, 'Update bookings: 2rooms, 3 passengers, 4 packages', 'BookingUpdate');
