INSERT INTO port (name, country, state, address, nearest_airport, parking_spots, status)
VALUES ('Port of Los Angeles', 'USA', 'California', '425 S Palos Verdes St, San Pedro, CA 90731',
        'Los Angeles International Airport', 500, 'ACTIVE'),
       ('Port of Long Beach', 'USA', 'California', '925 Harbor Plaza, Long Beach, CA 90802', 'Long Beach Airport', 350,
        'ACTIVE'),
       ('Port of Seattle', 'USA', 'Washington', '2711 Alaskan Way, Seattle, WA 98121',
        'Seattle-Tacoma International Airport', 400, 'ACTIVE'),
       ('Port of New York and New Jersey', 'USA', 'New York/New Jersey', '518 8th Ave, New York, NY 10018',
        'Newark Liberty International Airport', 600, 'ACTIVE'),
       ('Port of Houston', 'USA', 'Texas', '2100 E Loop N, Houston, TX 77029', 'George Bush Intercontinental Airport',
        300, 'ACTIVE'),
       ('Port of Miami', 'USA', 'Florida', '1015 N America Way, Miami, FL 33132', 'Miami International Airport', 700,
        'ACTIVE'),
       ('Port of Tampa Bay', 'USA', 'Florida', '1101 Channelside Dr, Tampa, FL 33602', 'Tampa International Airport',
        200, 'ACTIVE'),
       ('Port of San Diego', 'USA', 'California', '849 W Harbor Dr, San Diego, CA 92101',
        'San Diego International Airport', 250, 'ACTIVE'),
       ('Port of San Francisco', 'USA', 'California', 'Port of San Francisco, Embarcadero, San Francisco, CA 94111',
        'San Francisco International Airport', 400, 'ACTIVE'),
       ('Port of Baltimore', 'USA', 'Maryland', '2001 E Point Rd, Baltimore, MD 21226',
        'Baltimore/Washington International Airport', 150, 'ACTIVE'),
       ('Port of Charleston', 'USA', 'South Carolina', '196 Concord St, Charleston, SC 29401',
        'Charleston International Airport', 180, 'ACTIVE'),
       ('Port of Baton Rouge', 'USA', 'Louisiana', '1100 S River Rd, Baton Rouge, LA 70802',
        'Baton Rouge Metropolitan Airport', 100, 'ACTIVE'),
       ('Port of New Orleans', 'USA', 'Louisiana', '600 Port of New Orleans Pl, New Orleans, LA 70130',
        'Louis Armstrong New Orleans International Airport', 250, 'ACTIVE'),
       ('Port of Savannah', 'USA', 'Georgia', '1000 E President St, Savannah, GA 31404',
        'Savannah/Hilton Head International Airport', 120, 'ACTIVE'),
       ('Port of Wilmington', 'USA', 'North Carolina', '1710 S 3rd St, Wilmington, NC 28401',
        'Wilmington International Airport', 90, 'ACTIVE'),
       ('Port of Halifax', 'Canada', 'Nova Scotia', 'Port of Halifax, 1655 Lower Water St, Halifax, NS B3J 1S3',
        'Halifax Stanfield International Airport', 300, 'ACTIVE'),
       ('Port of Vancouver', 'Canada', 'British Columbia', '999 Canada Place, Vancouver, BC V6C 3T4',
        'Vancouver International Airport', 500, 'ACTIVE'),
       ('Port of Toronto', 'Canada', 'Ontario', 'Port of Toronto, 1 York St, Toronto, ON M5J 1B5',
        'Toronto Pearson International Airport', 400, 'ACTIVE'),
       ('Port of Montreal', 'Canada', 'Quebec', '220 Rue du Port, Montreal, QC H3C 1A9',
        'Montréal-Pierre Elliott Trudeau International Airport', 250, 'ACTIVE'),
       ('Port of St. John\'s', 'Canada', 'Newfoundland and Labrador', 'Port of St. John\'s, St. John\'s, NL A1C 6L2',
        'St. John\'s International Airport', 100, 'ACTIVE'),
       ('Port of Mexico City', 'Mexico', 'Mexico City', 'Avenida del Puente, Mexico City, CDMX, Mexico',
        'Benito Juárez International Airport', 200, 'ACTIVE'),
       ('Port of Veracruz', 'Mexico', 'Veracruz', 'Calle Salvador Díaz Mirón 1600, Veracruz, Mexico',
        'General Heriberto Jara International Airport', 80, 'ACTIVE'),
       ('Port of Ensenada', 'Mexico', 'Baja California', 'Boulevard Costero 2, Ensenada, BC, Mexico',
        'Ensenada Airport', 60, 'ACTIVE'),
       ('Port of Cozumel', 'Mexico', 'Quintana Roo', 'Calle 2 Norte, Cozumel, QR, Mexico',
        'Cozumel International Airport', 150, 'ACTIVE'),
       ('Port of Mazatlán', 'Mexico', 'Sinaloa', 'Av. del Mar, Mazatlán, Sin, Mexico',
        'General Rafael Buelna International Airport', 90, 'ACTIVE'),
       ('Port of San Juan', 'Puerto Rico', 'San Juan', 'Paseo de la Fortaleza, San Juan, PR 00901',
        'Luis Muñoz Marín International Airport', 300, 'ACTIVE'),
       ('Port of Fort-de-France', 'Martinique', 'Fort-de-France', 'Place Pierre Nord, Fort-de-France 97200, Martinique',
        'Martinique Aimé Césaire International Airport', 120, 'ACTIVE'),
       ('Port of Nassau', 'Bahamas', 'Nassau', 'Nassau Harbour, Nassau, Bahamas',
        'Lynden Pindling International Airport', 250, 'ACTIVE'),
       ('Port of Bridgetown', 'Barbados', 'Bridgetown', 'Bridgetown Port, Bridgetown, Barbados',
        'Grantley Adams International Airport', 150, 'ACTIVE'),
       ('Port of Roseau', 'Dominica', 'Roseau', 'Bayfront, Roseau, Dominica', 'Douglas-Charles Airport', 80, 'ACTIVE'),
       ('Port of Castries', 'Saint Lucia', 'Castries', 'Vigie Marina, Castries, Saint Lucia',
        'Hewanorra International Airport', 100, 'ACTIVE'),
       ('Port of Kingston', 'Jamaica', 'Kingston', '120-134 Wharf, Kingston, Jamaica',
        'Norman Manley International Airport', 200, 'ACTIVE'),
       ('Port of St. Thomas', 'U.S. Virgin Islands', 'St. Thomas', '9-A 99A, St. Thomas, US Virgin Islands',
        'Cyril E. King Airport', 180, 'ACTIVE'),
       ('Port of Tortola', 'British Virgin Islands', 'Tortola', 'Road Town, Tortola, British Virgin Islands',
        'Tortola Airport', 70, 'ACTIVE'),
       ('Port of St. John\'s', 'Antigua and Barbuda', 'St. John\'s', 'Heritage Quay, St. John\'s, Antigua',
        'V.C. Bird International Airport', 90, 'ACTIVE'),
       ('Port of Saint-Pierre', 'Saint Pierre and Miquelon', 'Saint-Pierre',
        'Port of Saint-Pierre, Saint-Pierre, Saint Pierre and Miquelon', 'J. A. Rochebeau Airport', 50, 'ACTIVE'),
       ('Port of Aruba', 'Aruba', 'Aruba', 'Port of Oranjestad, Aruba', 'Queen Beatrix International Airport', 200,
        'ACTIVE'),
       ('Port of Curaçao', 'Curaçao', 'Curaçao', 'Schottegatweg Oost, Willemstad, Curaçao',
        'Hato International Airport', 300, 'ACTIVE');

