INSERT INTO stateroom (balcony_count, number_bath, number_beds, room_size, location_id, stateroom_id, stateroom_type, status) VALUES (2, 3, 6, 1000, 1, 1, 'The Haven Suite', 'ACTIVE');
INSERT INTO stateroom (balcony_count, number_bath, number_beds, room_size, location_id, stateroom_id, stateroom_type, status) VALUES (2, 3, 6, 1000, 2, 2, 'The Haven Suite', 'ACTIVE');
INSERT INTO stateroom (balcony_count, number_bath, number_beds, room_size, location_id, stateroom_id, stateroom_type, status) VALUES (2, 3, 6, 1000, 3, 3, 'The Haven Suite', 'ACTIVE');
INSERT INTO stateroom (balcony_count, number_bath, number_beds, room_size, location_id, stateroom_id, stateroom_type, status) VALUES (2, 3, 6, 1000, 4, 4, 'The Haven Suite', 'ACTIVE');
INSERT INTO stateroom (balcony_count, number_bath, number_beds, room_size, location_id, stateroom_id, stateroom_type, status) VALUES (2, 2, 4, 800, 1, 5, 'Club Balcony Suite', 'ACTIVE');
INSERT INTO stateroom (balcony_count, number_bath, number_beds, room_size, location_id, stateroom_id, stateroom_type, status) VALUES (2, 2, 4, 800, 2, 6, 'Club Balcony Suite', 'ACTIVE');
INSERT INTO stateroom (balcony_count, number_bath, number_beds, room_size, location_id, stateroom_id, stateroom_type, status) VALUES (2, 2, 4, 800, 3, 7, 'Club Balcony Suite', 'ACTIVE');
INSERT INTO stateroom (balcony_count, number_bath, number_beds, room_size, location_id, stateroom_id, stateroom_type, status) VALUES (2, 2, 4, 800, 4, 8, 'Club Balcony Suite', 'ACTIVE');
INSERT INTO stateroom (balcony_count, number_bath, number_beds, room_size, location_id, stateroom_id, stateroom_type, status) VALUES (1, 2, 4, 600, 1, 9, 'Family Large Balcony', 'ACTIVE');
INSERT INTO stateroom (balcony_count, number_bath, number_beds, room_size, location_id, stateroom_id, stateroom_type, status) VALUES (1, 2, 4, 600, 2, 10, 'Family Large Balcony', 'ACTIVE');
INSERT INTO stateroom (balcony_count, number_bath, number_beds, room_size, location_id, stateroom_id, stateroom_type, status) VALUES (1, 2, 4, 600, 3, 11, 'Family Large Balcony', 'ACTIVE');
INSERT INTO stateroom (balcony_count, number_bath, number_beds, room_size, location_id, stateroom_id, stateroom_type, status) VALUES (1, 2, 4, 600, 4, 12, 'Family Large Balcony', 'ACTIVE');
INSERT INTO stateroom (balcony_count, number_bath, number_beds, room_size, location_id, stateroom_id, stateroom_type, status) VALUES (1, 1.5, 4, 400, 1, 13, 'Family Balcony', 'ACTIVE');
INSERT INTO stateroom (balcony_count, number_bath, number_beds, room_size, location_id, stateroom_id, stateroom_type, status) VALUES (1, 1.5, 4, 400, 2, 14, 'Family Balcony', 'ACTIVE');
INSERT INTO stateroom (balcony_count, number_bath, number_beds, room_size, location_id, stateroom_id, stateroom_type, status) VALUES (1, 1.5, 4, 400, 3, 15, 'Family Balcony', 'ACTIVE');
INSERT INTO stateroom (balcony_count, number_bath, number_beds, room_size, location_id, stateroom_id, stateroom_type, status) VALUES (1, 1.5, 4, 400, 4, 16, 'Family Balcony', 'ACTIVE');
INSERT INTO stateroom (balcony_count, number_bath, number_beds, room_size, location_id, stateroom_id, stateroom_type, status) VALUES (0, 1, 2, 300, 1, 17, 'Oceanview window', 'ACTIVE');
INSERT INTO stateroom (balcony_count, number_bath, number_beds, room_size, location_id, stateroom_id, stateroom_type, status) VALUES (0, 1, 2, 300, 2, 18, 'Oceanview window', 'ACTIVE');
INSERT INTO stateroom (balcony_count, number_bath, number_beds, room_size, location_id, stateroom_id, stateroom_type, status) VALUES (0, 1, 2, 300, 3, 19, 'Oceanview window', 'ACTIVE');
INSERT INTO stateroom (balcony_count, number_bath, number_beds, room_size, location_id, stateroom_id, stateroom_type, status) VALUES (0, 1, 2, 300, 4, 20, 'Oceanview window', 'ACTIVE');
INSERT INTO stateroom (balcony_count, number_bath, number_beds, room_size, location_id, stateroom_id, stateroom_type, status) VALUES (0, 1, 2, 200, 1, 21, 'Inside stateroom', 'ACTIVE');
INSERT INTO stateroom (balcony_count, number_bath, number_beds, room_size, location_id, stateroom_id, stateroom_type, status) VALUES (0, 1, 2, 200, 2, 22, 'Inside stateroom', 'ACTIVE');
INSERT INTO stateroom (balcony_count, number_bath, number_beds, room_size, location_id, stateroom_id, stateroom_type, status) VALUES (0, 1, 2, 200, 3, 23, 'Inside stateroom', 'ACTIVE');
INSERT INTO stateroom (balcony_count, number_bath, number_beds, room_size, location_id, stateroom_id, stateroom_type, status) VALUES (0, 1, 2, 200, 4, 24, 'Inside stateroom', 'ACTIVE');
INSERT INTO stateroom (balcony_count, number_bath, number_beds, room_size, location_id, stateroom_id, stateroom_type, status) VALUES (0, 1, 1, 150, 1, 25, 'Studio stateroom', 'ACTIVE');
INSERT INTO stateroom (balcony_count, number_bath, number_beds, room_size, location_id, stateroom_id, stateroom_type, status) VALUES (0, 1, 1, 150, 2, 26, 'Studio stateroom', 'ACTIVE');
INSERT INTO stateroom (balcony_count, number_bath, number_beds, room_size, location_id, stateroom_id, stateroom_type, status) VALUES (0, 1, 1, 150, 3, 27, 'Studio stateroom', 'ACTIVE');
INSERT INTO stateroom (balcony_count, number_bath, number_beds, room_size, location_id, stateroom_id, stateroom_type, status) VALUES (0, 1, 1, 150, 4, 28, 'Studio stateroom', 'ACTIVE');
